In [6]:
import numpy as np

In [7]:

def scaled_dot_product_attention(Q, K, V):
    """
    Compute scaled dot-product attention.

    Args:
    - Q (np.array): Query matrix
    - K (np.array): Key matrix
    - V (np.array): Value matrix

    Prints:
    - Attention weights after softmax
    - Final output after multiplying weights with V
    """
    d_k = K.shape[1]

    # Dot product of Q and transpose of K
    scores = np.dot(Q, K.T)

    # Scale scores by sqrt(d_k)
    scaled_scores = scores / np.sqrt(d_k)

    # Apply softmax to get attention weights
    weights = np.exp(scaled_scores) / np.sum(np.exp(scaled_scores), axis=-1, keepdims=True)

    # Multiply weights by V to get output
    output = np.dot(weights, V)

    print("Attention Weights:\n", weights)
    print("Output:\n", output)

In [8]:
# Test Inputs
Q = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [9]:
scaled_dot_product_attention(Q, K, V)

Attention Weights:
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]
Output:
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]
